import { useEffect,useState } from 'react';
import { ArrowLeft,ArrowRight,Bookmark,ChevronRight,Play,Star } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useHome } from '../hooks/useMovieData';
import { useAppStore } from '../stores/useAppStore';
import { getBackdropUrl } from '../lib/images';
import { MovieRow } from '../components/common/MovieRow';
import { HeroSkeleton } from '../components/common/Skeletons';
import type { Movie } from '../types';
export function HomePage(){
 const {data,loading,error}=useHome();const navigate=useNavigate();const history=useAppStore(s=>s.history);const [active,setActive]=useState(0);const featured=data?.featured??[];
 useEffect(()=>{if(active>=featured.length&&featured.length)setActive(0)},[active,featured.length]);
 useEffect(()=>{if(featured.length<2)return;const t=window.setInterval(()=>setActive(v=>(v+1)%featured.length),6000);return()=>window.clearInterval(t)},[featured.length]);
 const movie=featured[active] as Movie|undefined;
 if(error)return <div className="grid min-h-[70vh] place-items-center p-6 text-center"><div><h1 className="text-2xl font-bold">Something went wrong.</h1><p className="mt-2 text-[var(--muted)]">We couldn't load Netfinder right now.</p><button onClick={()=>location.reload()} className="mt-6 rounded-full bg-[var(--text)] px-5 py-3 text-sm font-semibold text-[var(--bg)]">Try Again</button></div></div>;
 return <div>{loading?<HeroSkeleton/>:<section className="relative mt-2 min-h-[500px] overflow-hidden rounded-[1.6rem] sm:min-h-[600px] lg:min-h-[680px]">
 {featured.map((item,i)=><div key={item.id} className={'absolute inset-0 transition-opacity duration-700 '+(i===active?'opacity-100':'pointer-events-none opacity-0')}><img src={getBackdropUrl(item)??''} alt="" className="absolute inset-0 h-full w-full object-cover" onError={e=>e.currentTarget.style.display='none'}/><div className="absolute inset-0 bg-gradient-to-r from-black via-black/55 to-black/10"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent to-black/10"/></div>)}
 <div className="relative flex min-h-[500px] items-end p-6 pb-20 sm:min-h-[600px] sm:p-10 sm:pb-24 lg:p-14"><div className="max-w-2xl text-white"><div className="mb-4 flex flex-wrap items-center gap-2 text-xs font-medium text-white/75"><span className="rounded-full bg-white/10 px-3 py-1.5">Featured</span>{movie?.releaseDate&&<span>{movie.releaseDate.slice(0,4)}</span>}{movie?.rating!==undefined&&<span className="inline-flex items-center gap-1"><Star size={12} fill="currentColor"/>{movie.rating.toFixed(1)}</span>}{movie?.runtime&&<span>{Math.floor(movie.runtime/60)}h {movie.runtime%60}m</span>}</div><h1 className="max-w-3xl text-4xl font-black tracking-[-.055em] sm:text-6xl lg:text-7xl">{movie?.title}</h1><p className="mt-4 max-w-xl text-sm leading-6 text-white/72 sm:text-base">{movie?.overview}</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>movie&&navigate('/movie/'+movie.id)} className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-black"><Play size={17} fill="currentColor"/>Explore</button>{movie&&<button onClick={()=>useAppStore.getState().toggleWatchlist(movie)} className="inline-flex items-center gap-2 rounded-full border border-white/18 bg-white/8 px-5 py-3 text-sm font-semibold text-white"><Bookmark size={17}/>Watchlist</button>}</div></div></div>
 <div className="absolute bottom-5 right-5 flex gap-2"><button aria-label="Previous featured movie" onClick={()=>setActive(v=>(v-1+featured.length)%featured.length)} className="grid h-10 w-10 place-items-center rounded-full border border-white/15 bg-black/30 text-white"><ArrowLeft size={17}/></button><button aria-label="Next featured movie" onClick={()=>setActive(v=>(v+1)%featured.length)} className="grid h-10 w-10 place-items-center rounded-full border border-white/15 bg-black/30 text-white"><ArrowRight size={17}/></button></div>
 <div className="absolute bottom-6 left-6 flex gap-1.5">{featured.map((item,i)=><button key={item.id} aria-label={'Show featured '+(i+1)} onClick={()=>setActive(i)} className={'h-1.5 rounded-full '+(i===active?'w-7 bg-white':'w-2 bg-white/35')}/>)}</div></section>}
 {data?.sections.map(section=><MovieRow key={section.id} title={section.title} items={section.items}/>)}{history.length>0&&data&&<MovieRow title="Recently Viewed" items={history.map(h=>data.sections.flatMap(s=>s.items).find(m=>m.id===h.movieId)).filter(Boolean) as Movie[]}/>}
 <section className="mt-12 rounded-[1.6rem] border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--muted)]">Netfinder</p><h2 className="mt-2 text-2xl font-bold">Find something worth watching.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[var(--muted)]">A focused discovery experience with local watchlists and an API layer ready for your real metadata provider.</p><button onClick={()=>navigate('/discover')} className="mt-5 inline-flex items-center gap-1 text-sm font-semibold">Discover <ChevronRight size={16}/></button></section>
 </div>
}
